Runsafe/Framework

src/no/runsafe/framework/api/command/ICommandExecutor.java, src/no/runsafe/framework/api/command/argument/BooleanArgument.java, src/no/runsafe/framework/api/command/argument/EntityType.java, src/no/runsafe/framework/api/entity/ITNTPrimed.java, src/no/runsafe/framework/internal/Player.java, src/no/runsafe/framework/internal/extension/RunsafeServer.java, src/no/runsafe/framework/internal/wrapper/ObjectWrapper.java, src/no/runsafe/framework/internal/wrapper/entity/BukkitArmourStand.java, src/no/runsafe/framework/internal/wrapper/entity/BukkitTNTPrimed.java, src/no/runsafe/framework/minecraft/RunsafeConsole.java, src/no/runsafe/framework/minecraft/entity/RunsafeTNTPrimed.java, src/no/runsafe/framework/minecraft/event/player/RunsafePlayerKickEvent.java, src/no/runsafe/framework/minecraft/event/player/RunsafePlayerPreLoginEvent.java, src/no/runsafe/framework/minecraft/inventory/RunsafeInventory.java
Can now get UUIDs from command executors if they have a UUID as well as get UUIDs from the pre log in event.
Implements primed tnt entities.
Implements method to check if an inventory is empty.
Fixes some problems with arguments.
=> Better UUID support and a few additions.

src/no/runsafe/framework/api/command/ICommandExecutor.java, src/no/runsafe/framework/minecraft/RunsafeConsole.java
Implemented so all ICommandExecutors are able to be used in hashMaps.
=> Implement equals and hashCode methods for RunsafeConsole.

.idea/misc.xml, Framework.iml, ant.xml, src/no/runsafe/framework/api/IServer.java, src/no/runsafe/framework/api/player/IPlayerControl.java, src/no/runsafe/framework/internal/extension/RunsafeServer.java, src/no/runsafe/framework/internal/wrapper/BukkitServer.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java, src/no/runsafe/framework/minecraft/Effect.java, src/no/runsafe/framework/minecraft/Item.java
Reduces the number of warnings produced by almost half
=> Reduce deprecation

src/no/runsafe/framework/api/server/IPlayerProvider.java, src/no/runsafe/framework/internal/extension/RunsafeServer.java
Also throws in an IPlayer list to username list converter.
=> Implement methods for converting a list of UUIDs to IPlayers.

src/no/runsafe/framework/api/player/IPlayerControl.java, src/no/runsafe/framework/internal/database/jdbc/QueryExecutor.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java
=> Allow IPlayers to be passed as MySQL parameters

src/no/runsafe/framework/api/command/argument/OptionalArgument.java, src/no/runsafe/framework/api/command/argument/RequiredArgument.java, src/no/runsafe/framework/api/command/argument/StringArgumentSpecification.java, src/no/runsafe/framework/api/command/argument/TrailingArgument.java, src/no/runsafe/framework/internal/wrapper/block/BukkitNoteBlock.java, src/no/runsafe/framework/internal/wrapper/entity/BukkitEntity.java, src/no/runsafe/framework/minecraft/entity/RunsafeLivingEntity.java
- add documentation
- reduce deprecation
- Implements ability to set command arguments as upper or lower case.
=> a few changes

src/no/runsafe/framework/api/hook/IPlayerExtensions.java, src/no/runsafe/framework/api/hook/IPlayerLookupService.java, src/no/runsafe/framework/api/server/IPlayerManager.java, src/no/runsafe/framework/internal/extension/RunsafeServer.java, src/no/runsafe/framework/internal/hooks/PlayerExtensions.java
Intended to help with UUID conversion
=> Allow for getting a player's UUID directly from UserControl

src/no/runsafe/framework/api/entity/IAnimal.java, src/no/runsafe/framework/api/entity/IArmourStand.java, src/no/runsafe/framework/internal/wrapper/entity/BukkitArmourStand.java, src/no/runsafe/framework/minecraft/entity/RunsafeArmourStand.java, src/no/runsafe/framework/minecraft/entity/RunsafeLivingEntity.java
- Puts back in the armour stand interface
- Corrects a parameter name
- Makes IAnimal extend ILivingEntity
=> Armour stands

src/no/runsafe/framework/internal/wrapper/entity/BukkitBlockProjectileSource.java, src/no/runsafe/framework/minecraft/entity/RunsafeBlockProjectileSource.java
Attempt to fix issue where when a player would be shot by a projectile from a dispenser the console would spit out exceptions.
=> Fix issue with block projectile sources.

src/no/runsafe/framework/api/entity/animals/horses/INormalHorse.java, src/no/runsafe/framework/minecraft/entity/animals/horses/HorseColour.java, src/no/runsafe/framework/minecraft/entity/animals/horses/HorseStyle.java, src/no/runsafe/framework/minecraft/entity/animals/horses/RunsafeNormalHorse.java, src/no/runsafe/framework/tools/nms/EntityRegister.java
Add horse related enumerations for AdminToyBox
=> Horsing around

src/no/runsafe/framework/api/IBossBar.java, src/no/runsafe/framework/internal/wrapper/BukkitBossBar.java, src/no/runsafe/framework/internal/wrapper/ObjectWrapper.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java, src/no/runsafe/framework/minecraft/Item.java, src/no/runsafe/framework/minecraft/bossBar/BarColour.java, src/no/runsafe/framework/minecraft/bossBar/BarFlag.java, src/no/runsafe/framework/minecraft/bossBar/BarStyle.java, src/no/runsafe/framework/minecraft/bossBar/RunsafeBossBar.java, src/no/runsafe/framework/minecraft/entity/LivingEntity.java
we don't get a free boss bar with dergons anymore, putting them in the framework so we can have our own custom boss bars for dergons.
=> Add boss bars to the framework, fix issue with shoulder entities.

src/no/runsafe/framework/api/IBossBar.java, src/no/runsafe/framework/minecraft/bossBar/RunsafeBossBar.java
add way to throw a new list of players at boss bars and have those players be the only ones who can see the boss bar
intended for use in EventEngine and Dergons plugins
=> new way to set boss bar players

src/no/runsafe/framework/api/entity/IAreaEffectCloud.java, src/no/runsafe/framework/api/player/IPlayerInventory.java, src/no/runsafe/framework/internal/wrapper/ObjectWrapper.java, src/no/runsafe/framework/internal/wrapper/entity/BukkitAreaEffectCloud.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java, src/no/runsafe/framework/minecraft/entity/PassiveEntity.java, src/no/runsafe/framework/minecraft/entity/RunsafeAreaEffectCloud.java, src/no/runsafe/framework/tools/CompactUtil.java
new runsafe area of effect intended for use in fixing an issue with dergon fireballs
=> New runsafe area of effect entity handling, minor changes

src/no/runsafe/framework/internal/wrapper/ObjectWrapper.java, src/no/runsafe/framework/internal/wrapper/item/meta/BukkitSpawnEgg.java, src/no/runsafe/framework/minecraft/item/meta/RunsafeSpawnEgg.java
To help fix issues with mob spawners in ItemControl
=> Better way of dealing with spawn eggs

src/no/runsafe/framework/minecraft/Item.java
=> new dragons breath item

src/no/runsafe/framework/api/player/IPlayerNotification.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java
=> New method for sending a player local sign text.

src/default.yml, src/no/runsafe/framework/api/database/IQueryExecutor.java, src/no/runsafe/framework/api/database/IRow.java, src/no/runsafe/framework/api/database/IValue.java, src/no/runsafe/framework/internal/database/DataConverter.java, src/no/runsafe/framework/internal/database/QueryExecutorBase.java, src/no/runsafe/framework/internal/database/Row.java, src/no/runsafe/framework/internal/database/Value.java, src/no/runsafe/framework/internal/log/RunsafeLogFormatter.java
Important - Must update runsafe config with new defaults along with this or the console will not be happy
=> Start moving away from using org.joda.time

src/no/runsafe/framework/api/player/IPlayerNotification.java, src/no/runsafe/framework/internal/database/DataConverter.java, src/no/runsafe/framework/internal/wrapper/player/BukkitPlayer.java, src/no/runsafe/framework/minecraft/Sound.java
This time conversion method did work with most things, but it broke when I was testing it with temp bans. now it should work better
=> more sounds, fix time

src/no/runsafe/framework/internal/database/DataConverter.java
account for time zone difference
=> Fix grabbing time instants from sql

src/no/runsafe/framework/api/entity/IWitherBoss.java, src/no/runsafe/framework/internal/wrapper/ObjectWrapper.java, src/no/runsafe/framework/minecraft/entity/RunsafeWitherBoss.java
I'm planning on adding a /killboss command in admintoybox for killing EnderDragons and Withers and I need this to be able to see if an entity is a wither boss
=> Add wither boss interface

src/no/runsafe/framework/minecraft/Item.java
hopefully fixes bug with items not having data values
=> revert changes to getting items

src/no/runsafe/framework/api/database/IQueryExecutor.java, src/no/runsafe/framework/api/database/IRow.java, src/no/runsafe/framework/api/database/IValue.java, src/no/runsafe/framework/internal/database/DataConverter.java, src/no/runsafe/framework/internal/database/QueryExecutorBase.java, src/no/runsafe/framework/internal/database/Row.java, src/no/runsafe/framework/internal/database/Value.java
I wish to add configurable cooldowns to kits / shops, this should allow for easier storing of cooldown time in sql
=> Allow for storing a java.time.Duration in sql.

src/no/runsafe/framework/api/player/IPlayerInventory.java, src/no/runsafe/framework/internal/extension/player/RunsafePlayer.java
Every check for a player's inventory being full is currently unreliable because they don't take armor / offhand into account. this should make it easier to fix them
=> Add new method for getting number of free spaces in a player's inventory
